[package]
name = "betterboxd-server"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { version = "0.8", features = ["ws"] }
tower-http = { version = "0.6", features = ["fs"] }
tokio = { version = "1.53", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
betterboxd-core = { path = "../../crates/core" }
tokio-util = "0.7.19"
futures-util = "0.3.34"
rusqlite = "0.40.2"
uuid = { version = "1.26.0", features = ["v7"] }
